Repository DataDog/test-infra-definitions, pull requests merged in 2023-11, with the labels that each got.

#436 [docker] skip pulumi update warning
  Dockerfile
Labels: mergequeue-status: in_progress

#437 [docker] increase max attempts for calls to aws ssm
  .awsconfig
  Dockerfile
Labels: mergequeue-status: in_progress

#459 Add fakeintake WithImageURL parameter
  components/datadog/apps/fakeintake/fargateFakeintakeService.go
  scenarios/aws/fakeintake/fakeintakeparams/params.go
Labels: enhancement, go

#460 Define fakeintake healthcheck, enforce fakeintake health during deployment
  components/datadog/apps/fakeintake/fargateFakeintakeService.go
Labels: enhancement, go

#470 fix: remove health check command which breaks updateEnv
  components/datadog/apps/fakeintake/fargateFakeintakeService.go
Labels: bug, go

#475 Fix 2 fakeintakes creation when not using load balancers
  components/datadog/apps/fakeintake/fargateFakeintakeService.go
Labels: mergequeue-status: in_progress

#464 [CONTINT-3356] Allow running different k8s version kind clusters
  components/datadog/apps/nginx/k8s.go
  components/datadog/apps/prometheus/k8s.go
  components/datadog/apps/redis/k8s.go
  components/kubernetes/kind.go
  components/kubernetes/kind_versions.go
  scenarios/aws/kindvm/run.go
Labels: enhancement

#454 Implement notification for the Linux platform
  README.md
  tasks/tool.py
Labels: enhancement

#392 [task] 🤖 install pulumi plugins at setup
  .gitlab-ci.yml
  integration-tests/invoke_test.go
  integration-tests/testfixture/config.yaml
  tasks/doc.py
  tasks/setup.py
Labels: mergequeue-status: in_progress

#485 [APL-2554] Add an agent to monitor the fake intake
  common/utils/json.go
  components/datadog/apps/fakeintake/fargateFakeintakeService.go
  components/datadog/apps/nginx/ecs.go
  components/datadog/apps/nginx/k8s.go
  components/datadog/apps/prometheus/ecs.go
  components/datadog/apps/prometheus/utils.go
  resources/aws/ecs/fargateService.go
Labels: mergequeue-status: in_progress
