Repository DataDog/test-infra-definitions, pull requests merged in 2023-12, with the labels that each got.

#494 [CONTINT-3310] Increase the fake intake memory
  components/datadog/apps/fakeintake/fargateFakeintakeService.go
  resources/aws/ecs/fargateService.go
  scenarios/aws/ecs/run.go
Labels: mergequeue-status: in_progress

#495 [CONTINT-3310] Increase the Redis app verbosity
  components/datadog/apps/redis/k8s.go
Labels: mergequeue-status: removed

#493 Rerun destroy with refresh on failure
  tasks/destroy.py
Labels: mergequeue-status: in_progress

#508 Use last version of install_script on all cases
  components/os/unix.go
Labels: bug

#509 Use latest version of the agent to monitor fakeintake
  components/datadog/agent/ecsFargate.go
  resources/aws/ecs/fargateService.go
Labels: mergequeue-status: in_progress

#512 [CONTINT-52] Start the agent with host network on kind
  scenarios/aws/kindvm/run.go
Labels: mergequeue-status: in_progress

#501 [docker] Add support for fakeintake and logs in agent docker
  components/command/docker.go
  components/datadog/agent/docker.go
  components/datadog/agent/docker/daemon.go
  components/datadog/agent/dockerparams/agentParams.go
  components/datadog/agent/dockerparams/params.go
  components/datadog/agent/ecs.go
  components/datadog/agent/ecsFargate.go
  components/datadog/agent/helm.go
  components/datadog/dockeragentparams/params.go
  go.mod
  scenarios/aws/dockerVM/run.go
  tasks/docker.py
Labels: enhancement, mergequeue-status: in_progress, team/agent-platform

#519 Fix a format string vulnerability
  components/datadog/agent/ecsFargate.go
Labels: mergequeue-status: in_progress

#500 [CONTINT-3407] Add dogstatsd workloads in dockervm scenario
  components/datadog/agent/docker.go
  components/datadog/apps/dogstatsd/docker-compose.yaml
  components/datadog/apps/dogstatsd/docker.go
  scenarios/aws/dockerVM/run.go
Labels: mergequeue-status: in_progress, team/agent-e2e-test

#517 remove unattended-upgrades on microvm instances
  scenarios/aws/microVMs/microvms/run.go
Labels: mergequeue-status: in_progress

#518 Make Windows installation work with WithPipelineID
  components/os/windows.go
  go.mod
  go.sum
Labels: mergequeue-status: in_progress
