Repository DataDog/test-infra-definitions, pull requests merged in 2024-11, with the labels that each got.

#1232 [aws][ec2] query redhat AMIs by version
  components/os/linux_descriptors.go
  scenarios/aws/ec2/os_resolver.go
Labels: mergequeue-status: in_progress

#1234 [aws][ec2] update fedora ami query
  components/os/linux_descriptors.go
  scenarios/aws/ec2/os_resolver.go
Labels: mergequeue-status: in_progress

#1235 [tasks] avoid closing test-infra bump PR not based on main
  tasks/ci.py
Labels: mergequeue-status: in_progress

#1241 [aws][ec2] add support for imds2 in ec2 resource
  resources/aws/ec2/vm.go
  scenarios/aws/ec2/vm.go
  scenarios/aws/ec2/vmargs.go
Labels: mergequeue-status: in_progress

#1244 feat(origin detection): make unified setting as default and implement external-data E2E test
  components/datadog/agent/kubernetes_helm.go
  components/datadog/apps/dogstatsd/images/dogstatsd/main.go
  components/datadog/apps/dogstatsd/k8s.go
Labels: enhancement

#1243 Changed ECR -> registry.ddbuild.io and updated build images
  .gitlab-ci.yml
Labels: mergequeue-status: in_progress

#1247 fix(dogstatsd-external-data-only): fix missing tag
  components/datadog/apps/dogstatsd/images/dogstatsd/main.go
Labels: bug

#1248 Adding JMX support to e2e tests
  components/datadog/agent/docker.go
  components/datadog/apps/jmxfetch/docker-compose-all-metrics.yaml
  components/datadog/apps/jmxfetch/docker-compose-slow-metrics.yaml
  components/datadog/apps/jmxfetch/docker.go
  components/datadog/apps/jmxfetch/images/jmx-test-app/SimpleApp.java
  components/datadog/dockeragentparams/params.go
Labels: mergequeue-status: in_progress

#1261 Sanitize the dependencies between K8s fake app pulumi components and the agent
  scenarios/aws/eks/run.go
  scenarios/aws/kindvm/run.go
  scenarios/azure/aks/run.go
  scenarios/gcp/gke/run.go
Labels: mergequeue-status: in_progress

#1240 Podman based local host
  common/config/environment.go
  components/datadog/agentparams/params.go
  components/remote/component.go
  components/remote/connection.go
  components/remote/connectionargs.go
  components/remote/os.go
  registry/scenarios.go
  resources/hyperv/vm.go
  resources/local/environment.go
  resources/local/podman/data/Dockerfile
  resources/local/podman/vm.go
  scenarios/aws/ec2/vm.go
  scenarios/aws/microVMs/microvms/provision.go
  scenarios/azure/compute/vm.go
  scenarios/gcp/compute/vm.go
  scenarios/local/podman/run/vm_run.go
  scenarios/local/podman/vm.go
  tasks/__init__.py
  tasks/config.py
  tasks/localpodman/__init__.py
  tasks/localpodman/vm.py
  tasks/tool.py
Labels: mergequeue-status: in_progress

#1265 Revert "Sanitize the dependencies between K8s fake app pulumi components and the agent"
  scenarios/aws/eks/run.go
  scenarios/aws/kindvm/run.go
  scenarios/azure/aks/run.go
  scenarios/gcp/gke/run.go
Labels: mergequeue-status: in_progress

#1266 Updating docker image checks to make sure JMX image available and used for pipelines
  common/config/environment.go
  common/utils/docker.go
  common/utils/docker_test.go
  components/datadog/agent/docker.go
  components/datadog/dockeragentparams/params.go
  resources/aws/environment.go
  resources/azure/environment.go
  resources/gcp/environment.go
  resources/hyperv/environment.go
  resources/local/environment.go
Labels: mergequeue-status: in_progress
