Repository DataDog/test-infra-definitions, pull requests merged in 2024-03, with the labels that each got.

#665 Add silent, show-error, fail and retries to curl commands
  components/datadog/agent/host_linuxos.go
  components/docker/docker.go
  components/kubernetes/kind.go
Labels: mergequeue-status: in_progress

#668 Revert "Add silent, show-error, fail and retries to curl commands"
  components/datadog/agent/host_linuxos.go
  components/docker/docker.go
  components/kubernetes/kind.go
Labels: mergequeue-status: in_progress

#674 [docker] enforce http on fakeintake with http scheme
  components/datadog/dockeragentparams/params.go
Labels: mergequeue-status: in_progress

#671 Revert "Revert "Add silent, show-error, fail and retries to curl commands""
  Dockerfile
  components/datadog/agent/host_linuxos.go
  components/docker/docker.go
  components/kubernetes/kind.go
  integration-tests/invoke_test.go
  tasks/docker.py
Labels: mergequeue-status: in_progress

#681 fix(install-script): Fix curl retry to reduce flakiness
  components/datadog/agent/host_linuxos.go
Labels: mergequeue-status: in_progress

#682 [kind] fix kind deployment
  components/kubernetes/kind.go
  integration-tests/invoke_test.go
  integration-tests/testfixture/config.yaml
  scenarios/aws/kindvm/run.go
  tasks/__init__.py
  tasks/kind.py
Labels: mergequeue-status: in_progress

#685 Fix(e2e): Set dependencies correctly to reduce test flakiness
  components/datadog/agentparams/params.go
  components/datadog/dockeragentparams/params.go
  components/datadog/kubernetesagentparams/params.go
Labels: mergequeue-status: in_progress

#677 [apps] use common signature for k8s apps
  .pre-commit-config.yaml
  components/datadog/apps/cpustress/k8s.go
  components/datadog/apps/dogstatsd/k8s.go
  components/datadog/apps/mutatedbyadmissioncontroller/k8s.go
  components/datadog/apps/nginx/k8s.go
  components/datadog/apps/prometheus/k8s.go
  components/datadog/apps/redis/k8s.go
  components/datadog/apps/tracegen/k8s.go
  components/datadog/dogstatsd-standalone/k8s.go
  components/kubernetes/component.go
Labels: mergequeue-status: in_progress

#631 Support macOS in KMT scenarios
  requirements.txt
  scenarios/aws/microVMs/config/config.go
  scenarios/aws/microVMs/microvms/domain.go
  scenarios/aws/microVMs/microvms/libvirt.go
  scenarios/aws/microVMs/microvms/libvirt_fs.go
  scenarios/aws/microVMs/microvms/network.go
  scenarios/aws/microVMs/microvms/pool.go
  scenarios/aws/microVMs/microvms/provision.go
  scenarios/aws/microVMs/microvms/resources/amd64.go
  scenarios/aws/microVMs/microvms/resources/arm64.go
  scenarios/aws/microVMs/microvms/resources/distro.go
  scenarios/aws/microVMs/microvms/resources/distro/domain-arm64.xsl
  scenarios/aws/microVMs/microvms/resources/resources.go
  scenarios/aws/microVMs/microvms/run.go
  tasks/__init__.py
  tasks/microvm-sample-xmls/domain.xml
  tasks/test.py
Labels: mergequeue-status: in_progress

#694 Fix lint-go
  scenarios/aws/microVMs/microvms/resources/distro.go
Labels: mergequeue-status: in_progress

#689 [create-vm-verify-pipeline] Added pipeline verification to deploy
  requirements.txt
  tasks/__init__.py
  tasks/deploy.py
  tasks/doc.py
  tasks/pipeline.py
  tasks/tool.py
  tasks/vm.py
Labels: mergequeue-status: in_progress, team/agent-platform

#697 [ASCII-1318] Add `WithSkipAPIKeyInAgentConfig` option
  components/datadog/agent/host.go
  components/datadog/agentparams/params.go
Labels: mergequeue-status: in_progress

#702 [CONTINT-3935] Create a priorityClass for the agent
  components/datadog/agent/kubernetes_helm.go
Labels: mergequeue-status: in_progress

#698 [NPM] add npm-tools k8s workload
  components/datadog/apps/npm-tools/k8s.go
Labels: enhancement, go, mergequeue-status: in_progress, team/agent-e2e-test

#705 CI(auto-bump): Automatically create test-infra bump PR on datadog-agent
  .github/workflows/auto-bump-datadog-agent.yml
Labels: mergequeue-status: in_progress

#713 Use latest nightly version of the agent instead of stable as default
  components/datadog/agent/host_linuxos.go
  components/datadog/agent/host_windowsos.go
  components/datadog/agentparams/params.go
  components/datadog/agentparams/params_test.go
  components/datadog/agentparams/version.go
Labels: mergequeue-status: in_progress

#721 Fix HPA settings to make them more reactive
  components/datadog/apps/nginx/k8s.go
Labels: mergequeue-status: in_progress

#722 Add netflow-generator workload app.
  .github/workflows/docker-publish.yml
  components/datadog/apps/netflow-generator/images/netflow-generator/Dockerfile
Labels: mergequeue-status: in_progress

#717 e2e(kubernetes agent): Change WithHelmValues to not override everytime but to merge them
  components/datadog/kubernetesagentparams/params.go
Labels: mergequeue-status: in_progress
