Repository DataDog/test-infra-definitions, pull requests merged in 2024-02, with the labels that each got.

#597 tracegen: bump dd trace go and define owners
  .github/CODEOWNERS
  components/datadog/apps/tracegen/images/tracegen/go.mod
  components/datadog/apps/tracegen/images/tracegen/go.sum
Labels: mergequeue-status: in_progress

#602 APL-2848 Handle pipeline id and commit sha to set docker image
  common/config/environment.go
  components/datadog/agent/docker.go
  components/datadog/agent/docker_image.go
  components/datadog/dockeragentparams/params.go
  components/datadog/dogstatsd-standalone/docker_image.go
  components/datadog/dogstatsd-standalone/k8s.go
  resources/aws/const.go
Labels: mergequeue-status: in_progress

#610 [NPM] teste2e go-httpbin and npm-tools Docker images
  components/datadog/apps/npm-tools/images/go-httpbin/Dockerfile
  components/datadog/apps/npm-tools/images/npm-tools/Dockerfile
Labels: docker, mergequeue-status: in_progress, team/agent-e2e-test

#603 [setup] add pulumi params to config
  integration-tests/invoke_test.go
  tasks/config.py
  tasks/deploy.py
  tasks/setup.py
Labels: mergequeue-status: in_progress

#611 [os] descriptor from string defaults to default descriptor
  components/os/descriptor.go
  scenarios/aws/ec2/vm_run.go
  scenarios/azure/compute/vm_run.go
Labels: mergequeue-status: in_progress

#612 [NPM] add npm docker images apps
  .github/dependabot.yml
  .github/workflows/docker-publish.yml
Labels: dependencies, docker, mergequeue-status: in_progress

#614 [host] increase agent installer curl retry
  components/datadog/agent/host_linuxos.go
Labels: mergequeue-status: in_progress

#617 fix docker publish workflow
  .github/workflows/docker-publish.yml
Labels: mergequeue-status: in_progress

#623 [gitlab] get github_token from app
  .github/jwt.sh
  .gitlab-ci.yml
  Dockerfile
Labels: mergequeue-status: in_progress

#622 [ECS] enable NPM in the agent
  components/datadog/agent/ecs.go
  components/datadog/ecsagentparams/params.go
Labels: enhancement, mergequeue-status: in_progress, team/agent-e2e-test

#625 [gitlab] store private key in memory
  .github/jwt.sh
  .gitlab-ci.yml
Labels: mergequeue-status: in_progress

#628 Use public.ecr.aws redis image to avoid rate limit
  components/datadog/apps/redis/ecs.go
  components/datadog/apps/redis/ecsFargate.go
  components/datadog/apps/redis/k8s.go
Labels: bug, mergequeue-status: in_progress, team/agent-e2e-test

#629 Add checks for encrypted keys and pulumi creds to setup.debug
  tasks/config.py
  tasks/setup.py
Labels: mergequeue-status: in_progress

#627 Add standalone uploader to upload tests at the end of test run
  Dockerfile
Labels: mergequeue-status: in_progress

#634 Add pre-commit hooks corresponding to GitHub workflows
  .pre-commit-config.yaml
  pyproject.toml
Labels: mergequeue-status: in_progress

#632 Create interface for parameter cross cloud providers
  common/config/environment.go
  resources/aws/environment.go
  resources/aws/environmentDefaults.go
  resources/azure/environment.go
  resources/hyperv/environment.go
  scenarios/aws/microVMs/microvms/run.go
Labels: mergequeue-status: in_progress

#626 [ECS] workload ECS for NPM tests
  components/datadog/apps/npm-tools/ecs.go
Labels: enhancement, mergequeue-status: in_progress, team/agent-e2e-test

#618 APL-2847 Create KubernetesAgent component to install the agent in Kubernetes
  components/datadog/agent/kubernetes.go
  components/datadog/agent/kubernetes_helm.go
  components/datadog/kubernetesagentparams/params.go
Labels: mergequeue-status: in_progress

#640 [ECS] add parameter WithNetworkMode
  components/datadog/agent/ecs.go
  components/datadog/ecsagentparams/params.go
Labels: enhancement, go, mergequeue-status: in_progress, team/agent-e2e-test

#605 Fix retry on agent install for pipelines
  components/datadog/agent/host_linuxos.go
Labels: mergequeue-status: in_progress
