Repository DataDog/test-infra-definitions, pull requests merged in 2024-04, with the labels that each got.

#735 Adding a Simple Java app to allow testing JMXFetch with the Agent
  .github/workflows/docker-publish.yml
  components/datadog/apps/jmxfetch/docker-compose.yaml
  components/datadog/apps/jmxfetch/docker.go
  components/datadog/apps/jmxfetch/images/jmx-test-app/Dockerfile
  components/datadog/apps/jmxfetch/images/jmx-test-app/SimpleApp.java
  components/datadog/apps/jmxfetch/images/jmx-test-app/run.sh
Labels: mergequeue-status: in_progress

#720 Istio component
  components/kubernetes/istio/istio.go
Labels: enhancement, mergequeue-status: in_progress, team/agent-e2e-test

#740 [KMT] Ensure docker config folder exists
  scenarios/aws/microVMs/microvms/provision.go
Labels: mergequeue-status: in_progress

#734 Add basic RPM support to the updater tests
  components/datadog/updater/install.go
  components/datadog/updater/install_script.sh
Labels: mergequeue-status: in_progress

#739 Move job to bump datadog-agent from Github to Gitlab
  .github/workflows/auto-bump-datadog-agent.yml
  .gitlab-ci.yml
  requirements.txt
  tasks/__init__.py
  tasks/ci.py
Labels: mergequeue-status: in_progress

#744 Increase `ec2_metadata_timeout` to avoid timeouts causing flakiness
  components/datadog/agent/kubernetes_helm.go
Labels: mergequeue-status: in_progress

#762 Add WithFileWithPermissions to create files with predefined permissions
  components/datadog/agent/host.go
  components/datadog/agentparams/filepermissions/permissions.go
  components/datadog/agentparams/filepermissions/permissions_nix.go
  components/datadog/agentparams/params.go
  go.mod
  go.sum
Labels: mergequeue-status: queued

#773 Use private registry kind image
  common/config/environment.go
  components/kubernetes/kind.go
  resources/aws/environment.go
  resources/aws/environmentDefaults.go
  resources/azure/environment.go
  resources/hyperv/environment.go
  scenarios/aws/kindvm/run.go
Labels: mergequeue-status: in_progress

#774 [kind] mount host proc into kind node
  components/kubernetes/kind-cluster.yaml
Labels: mergequeue-status: in_progress

#776 [agent-qa] use new subnets
  .gitlab-ci.yml
  resources/aws/environmentDefaults.go
Labels: mergequeue-status: in_progress

#782 [ci] disable gitlab pipeline on mergequeue
  .gitlab-ci.yml
  repository.datadog.yaml
Labels: mergequeue-status: in_progress

#783 [deps] Bump dependencies from all passing dependabot bumps
  .github/workflows/docker-publish.yml
  .github/workflows/lint.yml
  go.mod
  go.sum
  requirements.txt
Labels: mergequeue-status: in_progress

#780 Add WindowsPermissions structure that can be used with WithFileWithPermissions
  components/datadog/agentparams/filepermissions/permissions_win.go
Labels: mergequeue-status: in_progress

#791 Set explicit resources requests and limits to the agent
  components/datadog/agent/kubernetes_helm.go
Labels: mergequeue-status: in_progress

#781 Creating e2e test for udp logs
  components/datadog/apps/logger/docker-compose.yaml
  components/datadog/apps/logger/docker.go
  components/datadog/apps/logger/example_payload.json
  components/datadog/apps/logger/images/logger/.dockerignore
  components/datadog/apps/logger/images/logger/Dockerfile
  components/datadog/apps/logger/images/logger/README.md
  components/datadog/apps/logger/images/logger/go.mod
  components/datadog/apps/logger/images/logger/go.sum
  components/datadog/apps/logger/images/logger/main.go
  components/datadog/apps/logger/images/logger/main_test.go
Labels: mergequeue-status: in_progress

#759 Allow usage of secondary range on EKS + Upgrade to Kube 1.29 default as 1.26 will be out of support soon
  common/config/environment.go
  components/datadog/apps/nginx/k8s.go
  components/datadog/apps/redis/k8s.go
  components/kubernetes/component.go
  components/kubernetes/crds/kubernetes/datadoghq/v1alpha1/datadogMetric.go
  components/kubernetes/crds/kubernetes/datadoghq/v1alpha1/init.go
  components/kubernetes/crds/kubernetes/datadoghq/v1alpha1/pulumiTypes.go
  components/kubernetes/crds/kubernetes/doc.go
  components/kubernetes/crds/kubernetes/init.go
  components/kubernetes/crds/kubernetes/meta/v1/pulumiTypes.go
  components/kubernetes/crds/kubernetes/provider.go
  components/kubernetes/crds/kubernetes/pulumi-plugin.json
  components/kubernetes/crds/kubernetes/pulumiUtilities.go
  components/kubernetes/kind_versions.go
  go.mod
  go.sum
  resources/aws/eks/eniConfig.go
  resources/aws/environment.go
  resources/aws/environmentDefaults.go
  scenarios/aws/eks/run.go
  scenarios/aws/kindvm/run.go
Labels: mergequeue-status: in_progress

#795 fix utils.MergeYaml function unmarshalling yaml data into the wrong variable
  common/utils/yaml.go
Labels: mergequeue-status: in_progress

#797 Making the logger server more robust
  components/datadog/apps/logger/images/logger/main.go
  components/datadog/apps/logger/images/logger/main_test.go
Labels: mergequeue-status: in_progress

#798 Updating CODEOWNERS with AML owned apps
  .github/CODEOWNERS
Labels: mergequeue-status: in_progress

#799 Increase the CPU limit of the agents to avoid starvation at startup
  components/datadog/agent/kubernetes_helm.go
Labels: mergequeue-status: in_progress

#803 Fix the collection of agent telemetry
  components/datadog/agent/ecs.go
  components/datadog/agent/ecsFargate.go
  components/datadog/agent/kubernetes_helm.go
Labels: mergequeue-status: in_progress

#804 Increase the CPU and memory limits of the agents to avoid starvation
  components/datadog/agent/kubernetes_helm.go
  tasks/kind.py
Labels: mergequeue-status: in_progress
