Repository DataDog/test-infra-definitions, pull requests merged in 2024-01, with the labels that each got.

#542 Use HTTP for process and orchestrator additional endpoints
  components/datadog/agent/helm.go
Labels: mergequeue-status: in_progress

#536 Dual-ship `contimage`, `contlcycle` and `sbom` payloads to the fakeintake
  components/datadog/agent/helm.go
Labels: mergequeue-status: in_progress

#550 feat(vm): clean the known hosts to prevent possible collision
  integration-tests/invoke_test.go
  tasks/doc.py
  tasks/vm.py
Labels: mergequeue-status: in_progress

#549 feat(logging): fakeintake is an agent option in VM scenario.
  tasks/vm.py
Labels: mergequeue-status: in_progress

#553 [CONTINT-3600] Support k8s versions 1.28 and 1.29 in kind
  components/kubernetes/kind_versions.go
Labels: enhancement, mergequeue-status: in_progress, team/agent-e2e-test

#558 Add retry on install errors in Pulumi install, fix -1 suffix issue with Windows
  components/datadog/agent/host_linuxos.go
  components/datadog/agent/host_windowsos.go
Labels: mergequeue-status: in_progress

#565 Fix Kind cluster name
  components/kubernetes/kind.go
  scenarios/aws/kindvm/run.go
Labels: mergequeue-status: in_progress

#573 components/datadog/apps: add tracegen application
  .github/workflows/docker-publish.yml
  components/datadog/apps/tracegen/images/tracegen/Dockerfile
  components/datadog/apps/tracegen/images/tracegen/go.mod
  components/datadog/apps/tracegen/images/tracegen/go.sum
  components/datadog/apps/tracegen/images/tracegen/main.go
Labels: mergequeue-status: in_progress

#575 Enable support of container image uncompressed layers for SBOM scans
  components/datadog/agent/kubernetes_helm.go
Labels: mergequeue-status: in_progress

#577 components/datadog/agent: add apm port mapping in docker & ecs
  components/datadog/agent/docker.go
  components/datadog/agent/ecs.go
Labels: mergequeue-status: in_progress

#584 Fix create-docker invoke task
  scenarios/aws/ec2/vm_run.go
Labels: mergequeue-status: in_progress, tototot

#581 docker agent compose up running in privileged, required by system-probe
  components/datadog/agent/docker.go
  components/docker/compose.go
Labels: bug, docker, mergequeue-status: in_progress, team/agent-e2e-test

#583 Collect agent telemetry
  components/datadog/agent/ecs.go
  components/datadog/agent/ecsFargate.go
  components/datadog/agent/kubernetes_helm.go
Labels: mergequeue-status: in_progress

#589 Set remote_configuration.no_tls_validation to true
  components/datadog/agent/ecs.go
  components/datadog/agent/kubernetes_helm.go
  components/datadog/dockeragentparams/params.go
Labels: mergequeue-status: in_progress

#586 [CONTINT-3706] Increase the fake intake memory
  scenarios/aws/eks/run.go
  scenarios/aws/fakeintake/fakeintake.go
  scenarios/aws/fakeintake/params.go
  scenarios/aws/kindvm/run.go
Labels: mergequeue-status: in_progress

#580 Add instance profile and configure creds helper to authorize pulling docker images from ECR
  resources/aws/ec2/vm.go
  resources/aws/environment.go
  resources/aws/environmentDefaults.go
  scenarios/aws/ec2/vm.go
  scenarios/aws/ec2/vm_run.go
  scenarios/aws/ec2/vmargs.go
Labels: mergequeue-status: in_progress

#592 Branden.clark/e2e debug
  README.md
  integration-tests/invoke_test.go
  requirements.txt
  tasks/__init__.py
  tasks/config.py
  tasks/doc.py
  tasks/setup.py
  tasks/tool.py
Labels: mergequeue-status: in_progress

#595 Fix incorrect param name used for instance profile
  resources/aws/environment.go
Labels: mergequeue-status: in_progress
