Repository DataDog/test-infra-definitions, pull requests merged in 2025-07, with the labels that each got.

#1575 EKS Fargate kubelet API Logging Infrastructure
  components/datadog/agent/k8ssidecar/auth.go
  components/datadog/agent/kubernetes_helm.go
  components/datadog/apps/dogstatsd/eksFargate.go
  components/datadog/apps/nginx/eksFargate.go
  components/datadog/apps/nginx/k8s.go
  components/datadog/apps/nginx/k8s/manifest.go
  components/datadog/apps/nginx/k8s/modifiers.go
  scenarios/aws/eks/run.go
Labels: mergequeue-status: in_progress

#1579 Allow user to setup GDB server with QEMU
  scenarios/aws/microVMs/config/config.go
  scenarios/aws/microVMs/microvms/domain.go
  scenarios/aws/microVMs/microvms/resources/distro/domain-amd64.xsl
  scenarios/aws/microVMs/microvms/run.go
Labels: mergequeue-status: in_progress

#1613 Try to find Windows packages on a pipeline-ID specific folder before common folder
  components/datadog/agent/package.go
Labels: mergequeue-status: in_progress

#1618 correct quoting for Windows platform
  tasks/setup.py
Labels: bug, python, team/agent-e2e-test

#1625 [GPUM]: wait for external signal to finish cuda-basic app
  components/datadog/apps/gpu/images/cuda-basic/cuda-basic.cu
Labels: mergequeue-status: removed

#1627 revert [GPUM]: wait for external signal to finish cuda-basic
  components/datadog/apps/gpu/images/cuda-basic/cuda-basic.cu
Labels: mergequeue-status: in_progress

#1639 refactor(runner): Pin `dda` version instead of pulling from `datadog-agent-buildimages`
  Dockerfile
Labels: mergequeue-status: in_progress
